### ISSUE TITLE
Openhab + Grafana + Reverseproxy in Docker

### ISSUE THREAD

**Issue by matthijsvisser** [wborn/openhab-grafana#16]
Hi,

I'm really struggling to get the Grafana webview panels to work with Openhab and Grafana behind a reverse proxy in Docker.

I get the following errors (in the Firefox console):

> SecurityError: Permission denied to get property "href" on cross-origin object smarthome-grafana.js:350

> TypeError: smartHomeSubscriber is undefined

Docker-compose file:
```
version: '2'

services:
   reverseproxy:
     image: reverseproxy
     ports:
     # openhab
     - 5001:5001
     restart: always

   openhab:
     depends_on:
     - reverseproxy
     image: "openhab/openhab:2.4.0"
     restart: always
     ports:
     - "8080:8080"
     - "8443:8443"
     volumes:
     - "/etc/localtime:/etc/localtime:ro"
     - "/etc/timezone:/etc/timezone:ro"
     - "/opt/openhab/addons:/openhab/addons"
     - "/opt/openhab/conf:/openhab/conf"
     - "/opt/openhab/userdata:/openhab/userdata"
     environment:
       OPENHAB_HTTP_PORT: "8080"
       OPENHAB_HTTPS_PORT: "8443"
       EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
       USER_ID: "999"
       GROUP_ID: "999"

   grafana:
     depends_on:
     - reverseproxy
     image: grafana/grafana:latest
     ports:
       - '3000:3000'
     volumes:
       - grafana-storage:/var/lib/grafana
       - grafana-conf:/etc/grafana
     environment:
       - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
       - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
       - GF_AUTH_ANONYMOUS_ENABLED=true
       - GF_USERS_ALLOW_SIGN_UP=false
       - GF_SERVER_ROOT_URL=http://localhost/grafana/
       - GF_ALLOW_EMBEDDING=true
volumes:
  grafana-storage:
    driver: local
  grafana-conf:
    driver: local
```

nginx.conf:
```
worker_processes 1;

events { worker_connections 1024; }

http {

    sendfile on;

    upstream docker-openhab {
        server openhab:8080;
#       server 20.0.0.210:8080;
    }

    server {
        listen 5001;
        server_name     localhost;
        location / {
#           auth_basic           "Restricted Access!";
#           auth_basic_user_file /etc/nginx/conf.d/.htpasswd;
            proxy_pass           http://docker-openhab;
#           proxy_pass           http://localhost:8080;
#           proxy_redirect       off;
            proxy_buffering      off;
            proxy_set_header     Host $http_host;
#           proxy_set_header     Host $host;
            proxy_set_header     X-Real-IP $remote_addr;
            proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
#           proxy_set_header     X-Forwarded-Host $server_name;
            proxy_set_header     X-Forwarded-Proto $scheme;
#           add_header           X-Frame-Options  ALLOWALL;
#           add_header         X-Frame-Options SAMEORIGIN;
        }

        location /grafana/ {
            proxy_pass         http://20.0.0.210:3000/;
#           proxy_pass         http://docker-grafana/;
#           add_header         X-Frame-Options ALLOWALL;
#           add_header         X-Frame-Options SAMEORIGIN;
        }
    }
}
```

sitemap:
```
sitemap default label="test"
{
Webview height=9 icon=none 
url="http://20.0.0.210:5001/static/combo-300px.html?dashboardItem=gf_dashboard&fromItem=temp_view&panelItem=gf_panel_temperature&w=000000"
}
```

```
// the prefix that is used for each Grafana panel URL
SMARTHOME_GRAFANA_DEFAULTS["urlPrefix"] = "http://20.0.0.210:5001/grafana";
```

Openhab can be accessed at:
http://20.0.0.210:5001
Grafana at:
http://20.0.0.210:5001/grafana

Your help is much appreciated, thank you!
